# Generated by Django 3.2.13 on 2022-05-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnonymousDisplayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_display_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCurrentFEmotionalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_emotional_state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmotionsTriggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggers', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_cover_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSocialUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='', max_length=255)),
                ('linkedin', models.CharField(default='', max_length=255)),
                ('twitter', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Talk2meUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_anonymous', models.BooleanField(default=False)),
                ('is_therapist', models.BooleanField(default=False)),
                ('profile_image_url', models.TextField(blank=True)),
                ('anonymous_display_name', models.CharField(blank=True, max_length=255)),
                ('user_bio', models.TextField(blank=True, max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('anonymous_profile_image_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useranonymousdisplayimage')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('profile_cover_image_url', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.userprofilecoverimage')),
                ('user_current_emotional_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usercurrentfemotionalstate')),
                ('user_emotions', models.ManyToManyField(to='core.UserEmotions')),
                ('user_emotions_triggers', models.ManyToManyField(to='core.UserEmotionsTriggers')),
                ('user_goals', models.ManyToManyField(to='core.UserGoals')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_social_urls', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.usersocialurls')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
