# Generated by Django 3.2.13 on 2022-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='talk2meuser',
            name='user_emotions',
            field=models.ManyToManyField(to='core.UserEmotions'),
        ),
    ]
