# Generated by Django 3.2.13 on 2022-05-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220523_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk2meuser',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='talk2meuser',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='useremotions',
            name='emotions',
            field=models.CharField(default='', max_length=30),
        ),
    ]
