# Generated by Django 3.2.13 on 2022-06-04 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_talk2meuser_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time_slot', models.TimeField()),
                ('second_time_slot', models.TimeField()),
                ('third_time_slot', models.TimeField()),
                ('fourth_time_slot', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TherapistBookingsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_number_of_sessions_per_day', models.SmallIntegerField(default=3)),
                ('therapist_schedule_days', models.CharField(choices=[('ALD', 'All days'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='ALD', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='therapist_number_of_sessions_per_day',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='therapist_schedule_days',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='therapist_time_slots_available',
        ),
        migrations.DeleteModel(
            name='SessionTimes',
        ),
        migrations.AddField(
            model_name='therapistbookingsschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabletimeslots',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.therapistbookingsschedule'),
        ),
    ]
