# Generated by Django 3.2.13 on 2022-05-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220525_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnonymousDisplayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_display_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='talk2meuser',
            name='anonymous_profile_image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.useranonymousdisplayimage'),
        ),
    ]
