# Generated by Django 3.2.13 on 2022-05-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220523_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk2meuser',
            name='anonymous_display_name',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='anonymous_profile_image_url',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='is_user_anonymous',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='user_bio',
        ),
        migrations.RemoveField(
            model_name='talk2meuser',
            name='user_emotions',
        ),
    ]
