# Generated by Django 3.2.13 on 2022-06-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220604_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletimeslots',
            name='booking',
        ),
        migrations.AddField(
            model_name='therapistbookingsschedule',
            name='available_time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.availabletimeslots'),
        ),
        migrations.AlterField(
            model_name='therapistbookingsschedule',
            name='therapist_schedule_days',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3),
        ),
    ]
