# Generated by Django 3.2.13 on 2022-05-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220525_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk2meuser',
            name='profile_cover_image_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofilecoverimage'),
        ),
        migrations.AlterField(
            model_name='talk2meuser',
            name='user_social_urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usersocialurls'),
        ),
    ]
