# Generated by Django 3.2.13 on 2022-05-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220523_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk2meuser',
            name='anonymous_display_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='talk2meuser',
            name='anonymous_profile_image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='talk2meuser',
            name='is_user_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk2meuser',
            name='profile_image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='talk2meuser',
            name='user_bio',
            field=models.TextField(default='', max_length=300),
        ),
    ]
