# Generated by Django 3.2.13 on 2022-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220604_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabletimeslots',
            old_name='first_time_slot',
            new_name='time_slot',
        ),
        migrations.RemoveField(
            model_name='availabletimeslots',
            name='fourth_time_slot',
        ),
        migrations.RemoveField(
            model_name='availabletimeslots',
            name='second_time_slot',
        ),
        migrations.RemoveField(
            model_name='availabletimeslots',
            name='third_time_slot',
        ),
        migrations.RemoveField(
            model_name='therapistbookingsschedule',
            name='available_time_slot',
        ),
        migrations.AddField(
            model_name='therapistbookingsschedule',
            name='available_time_slot',
            field=models.ManyToManyField(to='core.AvailableTimeSlots'),
        ),
    ]
