# Generated by Django 3.2.13 on 2022-05-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220525_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk2meuser',
            name='user_current_emotional_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usercurrentfemotionalstate'),
        ),
    ]
