# Generated by Django 3.2.13 on 2022-06-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220604_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistbookingsschedule',
            name='available_time_slot',
        ),
        migrations.AddField(
            model_name='availabletimeslots',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.therapistbookingsschedule'),
        ),
        migrations.AlterField(
            model_name='availabletimeslots',
            name='time_slot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='therapistbookingsschedule',
            name='therapist_number_of_sessions_per_day',
            field=models.IntegerField(),
        ),
    ]
