# Generated by Django 3.2.13 on 2022-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_talk2meuser_user_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk2meuser',
            name='user_emotions',
            field=models.ManyToManyField(to='core.UserEmotions'),
        ),
        migrations.AlterField(
            model_name='useremotions',
            name='emotions',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hopeful'), (2, 'excited'), (3, 'sad'), (4, 'anxious'), (5, 'frustrated'), (6, 'withdrawn'), (7, 'stressed'), (8, 'scared'), (9, 'lonely'), (10, 'happy'), (11, 'indifferent'), (12, 'angry'), (13, 'No feelings')], default=13),
        ),
    ]
