# Generated by Django 3.2.13 on 2022-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220605_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletimeslots',
            name='booking',
        ),
        migrations.AddField(
            model_name='therapistbookingsschedule',
            name='available_time_slot',
            field=models.ManyToManyField(to='core.AvailableTimeSlots'),
        ),
    ]
