# Generated by Django 3.2.13 on 2022-05-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220524_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk2meuser',
            name='user_emotions',
        ),
        migrations.AddField(
            model_name='talk2meuser',
            name='user_emotions',
            field=models.IntegerField(choices=[(1, 'Hopeful'), (2, 'Excited'), (3, 'Sad'), (4, 'Anxious'), (5, 'Frustrated'), (6, 'Withdrawn'), (7, 'Stressed'), (8, 'Scared'), (9, 'Lonely'), (10, 'Happy'), (11, 'Indifferent'), (12, 'Angry'), (13, 'Nofeelings')], default=13),
        ),
        migrations.DeleteModel(
            name='UserEmotions',
        ),
    ]
