# Generated by Django 3.2.13 on 2022-06-06 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220605_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk2meuser',
            name='user_organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='org_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
